package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"runtime"
	"runtime/debug"
	"strconv"
	"strings"
	"time"
)

// handleSetup runs an interactive wizard that generates a .env file.
func handleSetup() {
	scanner := bufio.NewScanner(os.Stdin)
	prompt := func(label, fallback string) string {
		if fallback != "" {
			fmt.Printf("  %s [%s]: ", label, fallback)
		} else {
			fmt.Printf("  %s: ", label)
		}
		scanner.Scan()
		v := strings.TrimSpace(scanner.Text())
		if v == "" {
			return fallback
		}
		return v
	}

	fmt.Println()
	fmt.Println("  table42 — Setup Wizard")
	fmt.Println("  ─────────────────────")
	fmt.Println()

	// Step 1: Auth
	fmt.Println("  Step 1: Resy Authentication")
	fmt.Println()
	fmt.Println("  Option A: Go to resy.com, log in, open DevTools (F12) → Console,")
	fmt.Println("  paste the contents of scripts/extract-resy-token.js, and paste the")
	fmt.Println("  copied string here.")
	fmt.Println()
	fmt.Println("  Option B: Enter your Resy email and password.")
	fmt.Println()
	authMethod := prompt("Paste token string, or type 'email' for email/password", "")

	var email, password, authToken, accountName string
	var paymentID int
	if authMethod != "email" && authMethod != "" && strings.Contains(authMethod, "|") {
		// Pasted token string format: token|name|paymentId
		parts := strings.SplitN(authMethod, "|", 3)
		authToken = parts[0]
		if len(parts) > 1 {
			accountName = parts[1]
		}
		if len(parts) > 2 {
			paymentID, _ = strconv.Atoi(parts[2])
		}
		fmt.Printf("  → Authenticated as %s\n", accountName)
	} else if authMethod == "email" {
		email = prompt("Resy email", "")
		password = prompt("Resy password", "")
	} else if authMethod != "" {
		// Assume raw JWT token
		authToken = authMethod
	}

	// Step 2: Venue
	fmt.Println()
	fmt.Println("  Step 2: Restaurant")
	fmt.Println("  Search by name or enter a venue ID directly.")
	fmt.Println()
	venueInput := prompt("Restaurant name or venue ID", "")

	var venueID int
	var venueName string
	if id, err := strconv.Atoi(venueInput); err == nil {
		venueID = id
		venueName = fetchVenueName(id)
		if venueName == "" {
			venueName = fmt.Sprintf("venue-%d", id)
		}
	} else {
		// Search
		results := searchVenues(venueInput)
		if len(results) == 0 {
			fmt.Println("  No venues found. Enter the venue ID manually from the Resy URL.")
			venueID, _ = strconv.Atoi(prompt("Venue ID", ""))
		} else {
			fmt.Println()
			for i, v := range results {
				fmt.Printf("  [%d] %s — %s, %s (ID: %d)\n", i+1, v.name, v.neighborhood, v.region, v.id)
			}
			fmt.Println()
			choice := prompt("Select number", "1")
			idx, _ := strconv.Atoi(choice)
			if idx >= 1 && idx <= len(results) {
				venueID = results[idx-1].id
				venueName = results[idx-1].name
			}
		}
	}

	if venueName != "" {
		fmt.Printf("  → %s (ID: %d)\n", venueName, venueID)
	}

	// Fetch lead time
	leadDays := 0
	if venueID > 0 {
		leadDays = fetchLeadTime(venueID)
		if leadDays > 0 {
			fmt.Printf("  → Reservations open %d days in advance\n", leadDays)
		}
	}

	// Step 3: Reservation details
	fmt.Println()
	fmt.Println("  Step 3: Reservation Details")
	fmt.Println()
	date := prompt("Date (YYYY-MM-DD)", "")
	timeStr := prompt("Preferred time (HH:MM)", "19:00")
	timeRange := prompt("Time range (e.g. 17:00-22:00, or empty for exact)", "17:00-22:00")
	partySize := prompt("Party size", "2")
	tableType := prompt("Table type (e.g. Indoor Dining, or empty for any)", "")

	// Step 4: Drop time
	fmt.Println()
	fmt.Println("  Step 4: Drop Time (optional)")
	fmt.Println("  If you know when reservations open, the bot will snipe at that exact moment.")
	fmt.Println("  Format: YYYY-MM-DDTHH:MM:SS-04:00 (ET) or leave empty for immediate mode.")
	fmt.Println()

	dropTime := ""
	if leadDays > 0 {
		// Calculate suggested drop date
		targetDate, _ := time.Parse("2006-01-02", date)
		if !targetDate.IsZero() {
			dropDate := targetDate.AddDate(0, 0, -leadDays)
			suggested := dropDate.Format("2006-01-02") + "T09:00:00-04:00"
			fmt.Printf("  Suggested: %s (based on %d-day lead time)\n", suggested, leadDays)
			dropTime = prompt("Drop time", suggested)
		} else {
			dropTime = prompt("Drop time (RFC3339)", "")
		}
	} else {
		dropTime = prompt("Drop time (RFC3339, or empty)", "")
	}

	// Step 5: Optional extras
	fmt.Println()
	fmt.Println("  Step 5: Optional")
	fmt.Println()
	webhook := prompt("Discord/Slack webhook URL (or empty)", "")
	capsolverKey := prompt("CAPSolver API key (or empty)", "")

	// Write .env
	fmt.Println()
	var env strings.Builder
	env.WriteString("# table42 configuration\n")
	env.WriteString("# Generated by ./table42 setup\n\n")

	if authToken != "" {
		env.WriteString("RESY_AUTH_TOKEN=" + authToken + "\n")
	} else {
		env.WriteString("RESY_EMAIL=" + email + "\n")
		env.WriteString("RESY_PASSWORD=" + password + "\n")
	}
	if accountName != "" {
		env.WriteString("RESY_ACCOUNT_NAME=" + accountName + "\n")
	}
	if paymentID > 0 {
		env.WriteString("RESY_PAYMENT_ID=" + strconv.Itoa(paymentID) + "\n")
	}

	env.WriteString("\n# " + venueName + "\n")
	env.WriteString("RESY_VENUE_ID=" + strconv.Itoa(venueID) + "\n")
	env.WriteString("RESY_DATE=" + date + "\n")
	env.WriteString("RESY_TIME=" + timeStr + "\n")
	if timeRange != "" {
		env.WriteString("RESY_TIME_RANGE=" + timeRange + "\n")
	}
	env.WriteString("RESY_PARTY_SIZE=" + partySize + "\n")
	if tableType != "" {
		env.WriteString("RESY_TABLE_TYPE=" + tableType + "\n")
	}
	if dropTime != "" {
		env.WriteString("RESY_DROP_TIME=" + dropTime + "\n")
	}

	env.WriteString("\n# Sniper tuning\n")
	env.WriteString("RESY_SHOTS=3\n")
	env.WriteString("RESY_MAX_BOOK=5\n")

	if capsolverKey != "" {
		env.WriteString("\n# Captcha\n")
		env.WriteString("RESY_CAPSOLVER_KEY=" + capsolverKey + "\n")
	}

	if webhook != "" {
		env.WriteString("\n# Notifications\n")
		env.WriteString("RESY_WEBHOOK=" + webhook + "\n")
	}

	env.WriteString("\nRESY_OUTPUT=json\n")

	// Check for existing .env
	if _, err := os.Stat(".env"); err == nil {
		overwrite := prompt("  .env already exists. Overwrite? (y/n)", "n")
		if overwrite != "y" {
			fmt.Println("  Saved to .env.new instead.")
			os.WriteFile(".env.new", []byte(env.String()), 0600)
			fmt.Println()
			fmt.Println("  Done! Review .env.new and rename to .env when ready.")
			return
		}
	}

	os.WriteFile(".env", []byte(env.String()), 0600)
	fmt.Println("  .env written!")
	fmt.Println()
	fmt.Println("  Next steps:")
	fmt.Println("    ./table42 test    — verify webhook")
	fmt.Println("    ./table42         — run the bot")
	fmt.Println()
}

type venueResult struct {
	id           int
	name         string
	neighborhood string
	region       string
}

// searchVenues searches for restaurants by name via the Resy API.
func searchVenues(query string) []venueResult {
	body, _ := json.Marshal(map[string]any{
		"query":    query,
		"per_page": 5,
	})

	req, _ := http.NewRequest("POST", "https://api.resy.com/3/venuesearch/search", bytes.NewReader(body))
	req.Header.Set("Authorization", resyAPIKey)
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/json")

	client := &http.Client{Timeout: 5 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return nil
	}
	data, _ := io.ReadAll(resp.Body)

	// Parse search results — nested structure: {"search":{"hits":[...]}}
	var parsed struct {
		Search struct {
			Hits []struct {
				ID           struct{ Resy int } `json:"id"`
				Name         string             `json:"name"`
				Neighborhood string             `json:"neighborhood"`
				Region       string             `json:"region"`
			} `json:"hits"`
		} `json:"search"`
	}
	json.Unmarshal(data, &parsed)

	var results []venueResult
	for _, h := range parsed.Search.Hits {
		results = append(results, venueResult{
			id:           h.ID.Resy,
			name:         h.Name,
			neighborhood: h.Neighborhood,
			region:       h.Region,
		})
	}
	return results
}

// fetchLeadTime gets the advance booking window for a venue.
func fetchLeadTime(venueID int) int {
	url := fmt.Sprintf("https://api.resy.com/2/config?venue_id=%d", venueID)
	req, _ := http.NewRequest("GET", url, nil)
	req.Header.Set("Authorization", resyAPIKey)
	req.Header.Set("Accept", "application/json")

	client := &http.Client{Timeout: 5 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return 0
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return 0
	}
	data, _ := io.ReadAll(resp.Body)

	return extractJSONNumber(data, []byte(`"lead_time_in_days":`))
}

// handleSnipe parses a Resy URL and runs the bot with the extracted config.
// Example: ./table42 snipe "https://resy.com/cities/new-york-ny/venues/lartusi-ny?date=2026-04-01&seats=2"
func handleSnipe(resyURL string) {
	loadDotEnv()

	// Parse URL
	u, err := url.Parse(resyURL)
	if err != nil {
		fatal("Invalid URL: %v", err)
	}

	// Extract slug from path: /cities/{location}/venues/{slug} or /cities/{location}/{slug}
	parts := strings.Split(strings.Trim(u.Path, "/"), "/")
	var slug, location string
	for i, p := range parts {
		if p == "venues" && i+1 < len(parts) {
			slug = parts[i+1]
			break
		}
		if p == "cities" && i+1 < len(parts) {
			location = parts[i+1]
		}
	}
	if slug == "" && len(parts) >= 3 {
		// Fallback: /cities/location/slug format
		slug = parts[len(parts)-1]
		location = parts[len(parts)-2]
	}

	// Extract query params
	date := u.Query().Get("date")
	seats := u.Query().Get("seats")
	if seats == "" {
		seats = "2"
	}

	if slug == "" {
		fatal("Could not parse venue from URL. Expected format: https://resy.com/cities/.../venues/slug?date=YYYY-MM-DD&seats=N")
	}

	fmt.Printf("[table42] Parsing URL...\n")
	fmt.Printf("[table42] Slug: %s | Location: %s | Date: %s | Seats: %s\n", slug, location, date, seats)

	// Look up venue by slug
	venueReq, _ := http.NewRequest("GET",
		fmt.Sprintf("https://api.resy.com/3/venue?url_slug=%s&location=%s", slug, location), nil)
	venueReq.Header.Set("Authorization", resyAPIKey)
	venueReq.Header.Set("Accept", "application/json")
	lookupClient := &http.Client{Timeout: 5 * time.Second}
	venueResp, err := lookupClient.Do(venueReq)

	var venueID int
	var vName string

	if err == nil && venueResp.StatusCode == 200 {
		data, _ := io.ReadAll(venueResp.Body)
		venueResp.Body.Close()
		venueID = extractJSONNumber(data, []byte(`"resy":`))
		vName = extractJSONValue(data, []byte(`"name":`))
	}

	// Fallback: search by slug
	if venueID == 0 {
		searchQuery := strings.ReplaceAll(slug, "-", " ")
		results := searchVenues(searchQuery)
		if len(results) > 0 {
			venueID = results[0].id
			vName = results[0].name
		}
	}

	if venueID == 0 {
		fatal("Could not find venue '%s'. Try ./table42 search \"%s\"", slug, strings.ReplaceAll(slug, "-", " "))
	}

	// Get lead time
	leadDays := fetchLeadTime(venueID)
	fmt.Printf("[table42] Found: %s (ID: %d)\n", vName, venueID)
	if leadDays > 0 {
		fmt.Printf("[table42] Reservations open %d days in advance\n", leadDays)
	}

	// Set env vars for the main flow
	os.Setenv("RESY_VENUE_ID", strconv.Itoa(venueID))
	if date != "" {
		os.Setenv("RESY_DATE", date)
	}
	os.Setenv("RESY_PARTY_SIZE", seats)

	// Set defaults if not already configured
	if os.Getenv("RESY_TIME") == "" {
		os.Setenv("RESY_TIME", "19:00")
	}
	if os.Getenv("RESY_TIME_RANGE") == "" {
		os.Setenv("RESY_TIME_RANGE", "17:00-22:00")
	}
	if os.Getenv("RESY_SHOTS") == "" {
		os.Setenv("RESY_SHOTS", "3")
	}
	if os.Getenv("RESY_MAX_BOOK") == "" {
		os.Setenv("RESY_MAX_BOOK", "5")
	}

	fmt.Printf("[table42] Config: %s on %s, party of %s, range %s\n",
		vName, os.Getenv("RESY_DATE"), seats, os.Getenv("RESY_TIME_RANGE"))
	fmt.Println()

	// Check auth
	hasAuth := os.Getenv("RESY_AUTH_TOKEN") != "" || os.Getenv("RESY_EMAIL") != ""

	if !hasAuth {
		fmt.Println("[table42] ⚠ No auth in .env!")
		fmt.Println("[table42] Run the token extractor first:")
		fmt.Println("[table42]   1. Go to https://resy.com and log in")
		fmt.Println("[table42]   2. Open DevTools (F12) → Console")
		fmt.Println("[table42]   3. Paste scripts/extract-resy-token.js")
		fmt.Println("[table42]   4. Paste output into .env as RESY_AUTH_TOKEN=...")
		fmt.Println("[table42]   5. Re-run: ./table42 snipe \"" + resyURL + "\"")
		return
	}

	// Run the normal bot flow with the extracted config
	fmt.Println("[table42] Starting bot...")
	cfg := loadConfig()
	tlog = newTimingLog()
	defer tlog.dump()

	// Auth
	if cfg.AuthToken == "" {
		if cfg.Email == "" || cfg.Password == "" {
			fatal("Set RESY_AUTH_TOKEN, or both RESY_EMAIL and RESY_PASSWORD.")
		}
		token, pid, err := getAuthToken(cfg.Email, cfg.Password)
		if err != nil {
			fatal("Auth failed: %v", err)
		}
		cfg.AuthToken = token
		if cfg.PaymentID == 0 && pid != 0 {
			cfg.PaymentID = pid
		}
	}
	authHeader = cfg.AuthToken
	initBaseHeaders()

	if cfg.PaymentID == 0 {
		id, err := getPaymentMethodID(cfg.AuthToken)
		if err != nil {
			logf("Warning: %v — using payment_id=0", err)
		} else {
			cfg.PaymentID = id
		}
	}

	// Build, warm, and book — same pipeline as main()
	venueName = vName
	findURL := buildFindURL(cfg.VenueID, cfg.Date, cfg.PartySize)
	findBody := buildFindBody(cfg.VenueID, cfg.Date, cfg.PartySize)
	client := buildClient()

	sendTestWebhook(cfg.WebhookURL)
	warmConnections(client, cfg.Shots, findURL, findBody)
	initBookPayload(cfg.PaymentID, cfg.CaptchaToken)
	runtime.GC()
	debug.SetGCPercent(-1)

	logf("Firing immediately...")
	slots := fireAvailabilityShots(client, cfg.Shots, findURL, findBody, "")
	bookSlots([]*http.Client{client}, cfg, slots)
}

// handleSearch searches for venues and prints results.
func handleSearch(query string) {
	if query == "" {
		fmt.Println("Usage: ./table42 search <restaurant name>")
		return
	}

	results := searchVenues(query)
	if len(results) == 0 {
		fmt.Println("No venues found.")
		return
	}

	for _, v := range results {
		lead := fetchLeadTime(v.id)
		leadStr := ""
		if lead > 0 {
			leadStr = fmt.Sprintf(" — %d days in advance", lead)
		}
		fmt.Printf("  %s — %s, %s (ID: %d)%s\n", v.name, v.neighborhood, v.region, v.id, leadStr)
	}
}
